name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        cibw_python: ["cp310-*"]
        cibw_arch: ["aarch64"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          submodules: true

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'
            
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      
      - name: e
        run: python -m pip install -U setuptools wheel

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS: ${{ matrix.cibw_arch }}

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
