name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        arch: ["aarch64"]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'
            
      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v1

      - name: Install Python Deps
        run: python -m pip install --upgrade setuptools pip wheel

      - name: Build Wheels (linux)
        if: startsWith(matrix.os, 'ubuntu')
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          ARCH: ${{ matrix.arch }}
        run: |
          case "${ARCH}" in
            x86_64)
              mlimg=manylinux1_x86_64
              ;;
            aarch64)
              mlimg=manylinux2014_aarch64
              ;;
            *)
              echo "Unsupported wheel arch: ${ARCH}" >&2
              exit 1
              ;;
          esac
          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/github/workspace:rw \
            --workdir=/github/workspace \
            -e GITHUB_WORKSPACE=/github/workspace \
            -e PYTHON_VERSION="${PYTHON_VERSION}" \
            --entrypoint=/github/workspace/.github/workflows/build-manylinux-wheels.sh \
            quay.io/pypa/${mlimg}

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
